# Generated by Django 5.1.7 on 2025-04-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_destino_reseña_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseña',
            options={'ordering': ['-fecha']},
        ),
    ]
