services:
  - type: web
    name: travel-the-world
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Travel_the_World.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Travel_the_World.settings
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    region: oregon
    runtime: python
    branch: master
    rootDir: TercerEntrega/Travel_the_World


